### PR TITLE
Use git status to obtain list of local configurations

### PR DESCRIPTION
**Pull request by sergey-ostapenko**
Fixes https://github.com/mbtproject/mbt/issues/86

### CODE REVIEW

**Comment by sergey-ostapenko** [comment]
@buddyspike Could you take a look when you will have time?
I changed file trawers to usage of git status results. It works much faster now for local workspace.

**Comment by sergey-ostapenko** [comment]
Done, ready for review

**Comment by buddyspike** [comment]
@sergey-ostapenko Thank a lot for picking this one up.
Very clever implementation ;-)

I would like to propose a minor change if you don't mind.

Purpose of `Repo` component is to be a generic interface for reading repository. I feel like having a method like `DiscoverConfigs` would leak the specifics of filtering to `Repo`. Ideally, I think all knowledge about `.mbt.yml` should be in `Discover` component.

If we change `DiscoverConfigs` to something like `FindAllFilesInWorkspace(pathSpec string) (string[], error)`, we should be able to keep that separation clear.

Thoughts?

(BTW: Please squash all commits into 1)

**Comment by sergey-ostapenko** [comment]
@buddyspike done. Ready for review.

**Comment by buddyspike** [comment]
@sergey-ostapenko Awesome job! Thank you so much :-)

**Comment by buddyspike** [comment]
@sergey-ostapenko Sorry, it looks like the email you used in the commit is not the one you use in github. So github does not recognise you. You should add that as an additional email in your github account settings.

**Pull request merged**
