### PR TITLE
[WIP] Visualise the entirety of a filtered sub-graph

### PR DESCRIPTION
**Pull request by ojizero**
@buddyspike not sure if this is the best to go around the graph visualization, so I want to take your opinion about what I did, before I make more cleanups and write tests for it.

### CODE REVIEW

**Comment by buddyspike** [comment]
@ojizero, thanks. The approach looks good to me. Although, am I reading it correct that we are removing `--dependants` flag for regular output?

**Comment by ojizero** [comment]
@buddyspike that was just during my testing of the approach, I'll return it to it's old behaviour, guess I was too hasty commiting eveything 😅

**Comment by ojizero** [comment]
One note though, regarding the grouping in the output dot graph, if all the modules list contained the dependents, then the serialize method won't be able to distinguish them when coloring the dot graph, not sure of how to tackle it to be honest though 😅 Any ideas ?

**Comment by ojizero** [comment]
@buddyspike one last thing I want to ask 😅 what should we do with the older SerialAsDot and GroupedSerializeAsDot methods? Should the new Serialize renamed to SerializeAsDor (while remove gthe grouped verison), or should they be removed or have all three methods live together?

**Comment by buddyspike** [comment]
@ojizero I think `SerializeAsDot` still counts ;-)

**Comment by buddyspike** [comment]
>  if all the modules list contained the dependents, then the serialize method won't be able to distinguish them when coloring the dot graph

Not sure if I understand the concern correctly, is that because `ApplyFilters` does the expansion? It would be nice, if we could get the result with tags (i.e. `target`, `dependent`, `dependency`).

Another problem then is, when your search returns multiple results. In that case an item could be in more than one category. Have to give it a bit more thought 😉

**Comment by ojizero** [comment]
@buddyspike apologies for disappearing and not getting back on this PR 😓 I was kinda busy with life and work the past time !! I'll try to reimplement this within this week or the one after it and get back to you with a new PR 😬 😅

**Comment by buddyspike** [comment]
@ojizero No worries and thanks for dropping a note. We also have couple of new and high impact features on the roadmap. Hit me up if you are interested.

**Pull request closed without merging**
